### PR TITLE
Fix: dispatch autoheartbeat timers, send offline event dispatch

### PR DESCRIPTION
**Pull request by aregler**
This PR fixes 

- an issue where timers were not dispatched on the main queue, such that no heartbeat events were fired at all
- an issue where offline events were processed on the main queue (kinda unperformant because of the semaphore semantics when sending the event)
- log warnings where the FileManager tried to delete non-existing files

### CODE REVIEW

**Review by warchimede — APPROVED** [review]

**Review by lorrainNicolas — APPROVED** [review]

**Comment by BenDz** [comment]
Hey @aregler 
Thanks for your PR! We will review it asap

**Comment by warchimede** [comment]
Hello @BenDz,

The new `3.0.5` release from last week is conflicting with changes made in this PR.

Does it mean that the most recent version includes the fixes provided by @aregler or some similar code ?
If it is not the case, do you know when this PR will be reviewed and included ?

We are really looking forward to integrating a new version of Piano Analytics in which these issues are dealt with.

Thanks in advance 🙏🏽

**Comment by aregler** [comment]
Hey. Currently I am on parental leave and will review/update my PR(s) in a few weeks.

**Comment by aregler** [comment]
Hello @BenDz,

I updated my PR.
The timers still were not dispatched on the main queue. That's the reason why in our project no autoheartbeat timers would be fired at all.

Additionally I refactored the `sendStoredChunk` method.
Previously the offline event was sent and *afterwards* the offline file was deleted. This could lead to duplicate events, because the offline events are sent with a delay and  the `processSendEvents` method is called multiple times.
Having a greater number of offline evens (n > 10 was sufficient for my tests) could be in queue here:

image

while the send method is called again.

**Review by warchimede — APPROVED** [review]

**Comment by BenDz** [comment]
Hello,
Thank you for your inputs. We are currently reviewing it and plan to release it beginning of September along with our next update.

**Pull request closed without merging**
